# Changes here will be overwritten by Copier
_commit: 53a5901
_src_path: https://codeberg.org/Fresh2dev/copier-f2dv-project.git
author_email: hello@Fresh2.dev
author_name: Donald Mellenbruch
ci_domain_name: lokalhost.net
docs_url: https://www.Fresh2.dev/code/r/mockish/i
funding_url: https://www.Fresh2.dev/funding
home_page: https://www.Fresh2.dev
is_minimal: false
is_python: true
license_type: GPLv3
package_name: mockish
project_description: A thin layer of sugar atop Python's mock.
project_name: mockish
python_version: '3.7'
repo_mirror: https://www.Fresh2.dev/code/r/mockish
repo_url: https://github.com/fresh2dev/mockish
